/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystemssss;

import java.awt.Color;
import java.awt.MenuComponent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author 30310250
 */
    public class bookingsystem extends javax.swing.JFrame {

    
    public bookingsystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jstd = new javax.swing.JLabel();
        jpok = new javax.swing.JLabel();
        kjhk = new javax.swing.JLabel();
        jCB = new javax.swing.JLabel();
        std = new javax.swing.JRadioButton();
        jRbEco = new javax.swing.JRadioButton();
        jRbFirst = new javax.swing.JRadioButton();
        jRbSingle = new javax.swing.JRadioButton();
        jRbchildYes = new javax.swing.JRadioButton();
        jRbReturn = new javax.swing.JRadioButton();
        jRAdultyesYES = new javax.swing.JRadioButton();
        jgkds = new javax.swing.JLabel();
        Item = new javax.swing.JComboBox<>();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        mk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jC = new javax.swing.JTextField();
        jA = new javax.swing.JTextField();
        jType = new javax.swing.JTextField();
        jRstd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTo = new javax.swing.JTextField();
        JDate = new javax.swing.JTextField();
        jTime = new javax.swing.JTextField();
        jTicketNo = new javax.swing.JTextField();
        xs = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jRoute = new javax.swing.JTextField();
        jFrom = new javax.swing.JTextField();
        sad = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlblSubTotal00 = new javax.swing.JLabel();
        jlblTaxdc = new javax.swing.JLabel();
        ut = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jButtonTotal = new javax.swing.JButton();
        jlblsubTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Train Ticketing System");

        jLabel6.setFont(new java.awt.Font("Webdings", 0, 96)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jstd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jstd.setText("Class");

        jpok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jpok.setText("Ticket Type");

        kjhk.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kjhk.setText("Adult");

        jCB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCB.setText("Destination");

        std.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        std.setText("Standard");
        std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdActionPerformed(evt);
            }
        });

        jRbEco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRbEco.setText("Economy");

        jRbFirst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRbFirst.setText("First Class");

        jRbSingle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRbSingle.setText("Single");
        jRbSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbSingleActionPerformed(evt);
            }
        });

        jRbchildYes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRbchildYes.setText("Yes");

        jRbReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRbReturn.setText("Return");

        jRAdultyesYES.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRAdultyesYES.setText("Yes");
        jRAdultyesYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAdultyesYESActionPerformed(evt);
            }
        });

        jgkds.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jgkds.setText("Child");

        Item.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilburn", "Queens Park", "Oxford", "Casltemilk", "Manchester", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jstd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbEco, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRbReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpok, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kjhk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jgkds, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jRAdultyesYES, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jRbchildYes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jstd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpok)
                    .addComponent(kjhk)
                    .addComponent(jgkds))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRbSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRAdultyesYES, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRbchildYes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbEco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jRbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("From :");

        mk.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mk.setText("Ticket No  ...");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Adult");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Child");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("To :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("Date :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Class");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Time :");

        xs.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        xs.setText("Route");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setText("Ticket Type");

        sad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sad.setText("Price");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(40, 40, 40)
                                            .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(sad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74))
                                .addComponent(jTicketNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)))
                            .addComponent(xs, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jRstd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addComponent(mk, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRstd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(mk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sad)
                        .addGap(13, 13, 13)
                        .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblSubTotal00.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblSubTotal00.setText("Sub Total :");

        jlblTaxdc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblTaxdc.setText("Tax  :");

        ut.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ut.setText("Total  :");

        jlblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jlblTax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTaxActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTotalMouseClicked(evt);
            }
        });
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jlblsubTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblsubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblsubTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal00, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTaxdc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblsubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jlblTax)
                    .addComponent(jlblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal00)
                    .addComponent(jlblsubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTaxdc))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ut)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void checkTheLogin(){
 //programatically create the labels and texfields for the optionpane
 JLabel label_login = new JLabel("Username:");
 JTextField login = new JTextField();
 JLabel label_password = new JLabel("Password:");
 JPasswordField password = new JPasswordField();
 //-----------------------------------------------------
 // store these in an object array
 Object[] login_GUI_Elelemnts = { label_login, login, label_password, password };
 //-----------------------------------------------------
 int userInteraction = JOptionPane.showConfirmDialog(null, login_GUI_Elelemnts, "Login",
 JOptionPane.OK_CANCEL_OPTION,
 JOptionPane.PLAIN_MESSAGE);
// this integer variable 'userInteraction' will hold the result of
//the users interaction with the JOpttionPane
//we will then test the result against common returned values. OK OPtion , Cancel , Closed
//-----------------------------------------------------
 if (userInteraction == JOptionPane.OK_OPTION)
 {
 String user=login.getText().trim(); // user string that the user entered in the textfield
 String pass=new String(password.getPassword()); //pulls the password string from textfield
 Boolean entryGranted = false ;// setup boolean as false.
 if (( user.toUpperCase().equals ("USER")) && pass.toUpperCase().equals ("2"))
 {
 JOptionPane.showMessageDialog(this, "Logged in as user\nAdmin panel will be removed");
 //If an ordinary user logged in then remove the panel tabs that relate to administrators.
 this.jPanel6.remove(jLabel1); //removes the admin tab
     MenuComponent jPanel5 = null;
 this.jPanel6.remove(jPanel5); //removes the user crud tab
 entryGranted=true;
 }
 if (( user.toUpperCase().equals ("USER")) && pass.toUpperCase().equals ("1"))
 {
 JOptionPane.showMessageDialog(this, "Logged in as manager\nAccess granted to all areas");
 entryGranted=true;
 }
 if (!entryGranted) //entry denied
 {
 JOptionPane.showMessageDialog(this, "Go chase yourself - entry denied");
 userInteraction = JOptionPane.CANCEL_OPTION;
 }
 }
 else
 {//user clicked on CANCEL or the X close button- we change the userInteraction to force execution of the CANCEL block of code
 userInteraction = JOptionPane.CANCEL_OPTION;
 }
 if ( (userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION) )
 // the cancel block of code - if user presses the X or CANCEL
 {
 //feedback to user and close the application as no suitable login credentials have been supplied.
 JOptionPane.showMessageDialog(this, "You have not supplied valid credentials\n the application will now terminate");
 System.exit(0);
 
 }
    }
    
    
    
    private void jRbSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbSingleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:
        jlblsubTotal.setText(null);
        jlblTax.setText(null);
        jlblTotal.setText(null);
        jTicketNo.setText(null);
        jRoute.setText(null);
        jlblTotal.setText(null);
        jPrice.setText(null);
        
        jType.setText(null);
        jA.setText(null);
        jC.setText(null);
    }//GEN-LAST:event_ResetMouseClicked

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        // TODO add your handling code here:
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        jTime.setText(tTime.format(timer.getTime()));
  //#################################################################################
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyy");
        JDate.setText(Tdate.format(timer.getTime()));
     //######################################   
        jFrom.setText("london");
        jTo.setText((String) Item.getSelectedItem()+ "*");
      //##############RANDOM#########  
        int num1;
        String q1="";
        num1 = 1325 + (int) (Math.random()*4238);
        q1 += num1 = 1325;
        jTicketNo.setText(q1);
     //===============================================   
        jRoute.setText("ANY");
        
        //===========================
          jRstd.setText("First");
          jType.setText("Single");
          jA.setText("YES");
          jC.setText("no");
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButtonTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTotalMouseClicked
        // TODO add your handling code here:
        double tax = 19.50;
        double MilesK8 = 25.78;
        double MilesK12 = 25.10;
        double MilesK20 = 45.78;
        double MilesK30 = 55.78;
        double totalCost, eco = 3.85, fclass = 5.60;
        
        if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost - 18);
           jlblTotal.setText(Total);
            jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        }
   //===========================================kiliburn  std=================================================================     
   else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NULL");
        
        }
        
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NULL");
    
    
        }
  //##############################################queens park std###################################
  
     if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost - 18);
           jlblTotal.setText(Total);
            jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        }
        //#######################################oxford std ####################################
        
        
    else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("Null");
        
        }
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((std.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        
        else if ((std.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("STD");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
    
    
        }
        
   //############################################### Manchester std ##################################   
     
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + eco );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Kilburn")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost+ eco -18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco + totalCost - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("kiliburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
            jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NULL");
        }
//############## economical kiliburn ##########################

 else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + eco );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("one way");
           jA.setText("one");
           jC.setText("NIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NULL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost+ eco -18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco + totalCost - 18);
           jlblTotal.setText(Total);
            jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("ONE WAY");
           jA.setText("one");
           jC.setText("NULL");
        
        }
        
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Queens Park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£8.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);    
           jRstd.setText("economy");
           jType.setText("RETURN");
           jA.setText("one");
           jC.setText("NUIL");
        }
        //################################# Economey queens park###############################
        
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + eco );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("one way");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost+ eco -18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco + totalCost - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("ONE WAY");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jC.setText("one");
           jA.setText("NUIL");
        }
        //######################################### economy oxfod##################################
        
         else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + eco );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco +totalCost);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("one way");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£8.2f", totalCost);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost+ eco -18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£5.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco + totalCost - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("ONE WAY");
           jC.setText("one");
           jA.setText("NUIL");
        
        }
        
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("Manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTax.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblsubTotal.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           jlblTotal.setText(Total);
           jPrice.setText(Total);
           jRstd.setText("economy");
           jType.setText("RETURN");
           jC.setText("one");
           jA.setText("NULL");
        }
        //########################################## economy manchester ###################################///////nahom fist class take care
        
          else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("kiliburn")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + eco );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco +totalCost);
           ut.setText(Total);
           jSTD.setText("economy");
           jpok.setText("one way");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("kiliburn")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           ut.setText(Total);
           jSTD.setText("economy");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("kiliburn")){
        
           totalCost = (tax * (MilesK8 + eco) / 100);
           String sTax = String.format("£%.2f", totalCost+ eco -18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + eco + totalCost - 18);
           ut.setText(Total);
           jSTD.setText("economy");
           jpok.setText("ONE WAY");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("kiliburn")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           ut.setText(Total);
           jSTD.setText("economy");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        }
//############## first class kiliburn ##########################

 else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("queens park")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + fclass );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass +totalCost);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("one way");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("queens park")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("queens park")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost+ fclass -18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass + totalCost - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("ONE WAY");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("queens park")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        }
        //################################# first class queens park###############################
        
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("oxford")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + fclass );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass +totalCost);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("one way");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("oxford")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("oxford")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost+ fclass -18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass + totalCost - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("ONE WAY");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("oxford")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",((MilesK8 + totalCost) * 2) - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        }
        //######################################### first class oxfod##################################
        
         else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("manchester")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 + fclass );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass +totalCost);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("one way");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRAdultyesYES.isSelected()) && Item.getSelectedItem().equals("manchester")){
        
           totalCost = (tax * (MilesK8  * 2) / 100);
           String sTax = String.format("£%.2f", totalCost);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + totalCost * 2);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("manchester")){
        
           totalCost = (tax * (MilesK8 + fclass) / 100);
           String sTax = String.format("£%.2f", totalCost+ fclass -18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£%.2f",MilesK8 + fclass + totalCost - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("ONE WAY");
           kjhk.setText("one");
           jgkds.setText("NIL");
        
        }
        
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbchildYes.isSelected()) && Item.getSelectedItem().equals("manchester")){
        
           totalCost = (tax *MilesK8 / 100);
           String sTax = String.format("£%.2f", totalCost-18);
           jlblTaxdc.setText(sTax);
           String subTotal = String.format("£%.2f",MilesK8 );
           jlblSubTotal00.setText(subTotal);
           String Total = String.format("£8.2f",((MilesK8 + totalCost) * 2) - 18);
           ut.setText(Total);
           jSTD.setText("first");
           jpok.setText("RETURN");
           kjhk.setText("one");
           jgkds.setText("NIL");
        }
        //########################################## first class manchester ###################################


    }//GEN-LAST:event_jButtonTotalMouseClicked

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
         jlblsubTotal.setText(null);
        jlblTax.setText(null);
        jlblTotal.setText(null);
        jTicketNo.setText(null);
        jRoute.setText(null);
        jlblTotal.setText(null);
        jPrice.setText(null);
        jFrom.setText(null);
        jTo.setText(null);
        JDate.setText(null);
        jTime.setText(null);
        
        jType.setText(null);
        jRstd.setText(null);
        jA.setText(null);
        jC.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdActionPerformed

    private void jRAdultyesYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAdultyesYESActionPerformed
        
    }//GEN-LAST:event_jRAdultyesYESActionPerformed

    private void jlblsubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblsubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblsubTotalActionPerformed

    private void jlblTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTaxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       checkTheLogin();
    }//GEN-LAST:event_formWindowOpened

       
    
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Item;
    private javax.swing.JTextField JDate;
    private javax.swing.JButton Reset;
    private javax.swing.JButton exit;
    private javax.swing.JTextField jA;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JTextField jC;
    private javax.swing.JLabel jCB;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jPrice;
    private javax.swing.JRadioButton jRAdultyesYES;
    private javax.swing.JRadioButton jRbEco;
    private javax.swing.JRadioButton jRbFirst;
    private javax.swing.JRadioButton jRbReturn;
    private javax.swing.JRadioButton jRbSingle;
    private javax.swing.JRadioButton jRbchildYes;
    private javax.swing.JTextField jRoute;
    private javax.swing.JTextField jRstd;
    private javax.swing.JTextField jTicketNo;
    private javax.swing.JTextField jTime;
    private javax.swing.JTextField jTo;
    private javax.swing.JTextField jType;
    private javax.swing.JLabel jgkds;
    private javax.swing.JLabel jlblSubTotal00;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JLabel jlblTaxdc;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jlblsubTotal;
    private javax.swing.JLabel jpok;
    private javax.swing.JLabel jstd;
    private javax.swing.JLabel kjhk;
    private javax.swing.JLabel mk;
    private javax.swing.JLabel sad;
    private javax.swing.JRadioButton std;
    private javax.swing.JLabel ut;
    private javax.swing.JLabel xs;
    // End of variables declaration//GEN-END:variables

    private static class jTime {

        public jTime() {
        }
    }
}
